// This file is autogenerated by the hyperdispatch compiler
/* eslint-disable camelcase */

const { c, b4a, assert, DispatchError, ERRORS } = require("hyperdispatch/runtime");
const { version, getEncoding, setVersion } = require("./messages.js");

const defaultVersion = version;

class Router {
  constructor() {
    this._handler0 = null;
    this._handler1 = null;
    this._handler2 = null;

    this._missing = 3;
  }

  add(name, handler) {
    switch (name) {
      case "@pear-chat/add-writer":
        this._handler0 = handler;
        break;
      case "@pear-chat/add-invite":
        this._handler1 = handler;
        break;
      case "@pear-chat/add-message":
        this._handler2 = handler;
        break;
      default:
        throw DispatchError.NONEXISTENT_ROUTE(name);
    }
    this._missing--;
  }

  _checkAll() {
    assert(this._handler0 !== null, 'Missing handler for "@pear-chat/add-writer"');
    assert(this._handler1 !== null, 'Missing handler for "@pear-chat/add-invite"');
    assert(this._handler2 !== null, 'Missing handler for "@pear-chat/add-message"');
  }

  async dispatch(message, context) {
    if (this._missing > 0) {
      this._checkAll();
    }

    setVersion(defaultVersion);

    const op = b4a.isBuffer(message) ? decode(message) : message;

    switch (op.id) {
      case 0:
        return this._handler0(op.value, context);
      case 1:
        return this._handler1(op.value, context);
      case 2:
        return this._handler2(op.value, context);
      default:
        throw DispatchError.HANDLER_NOT_FOUND_BY_ID(op.id);
    }
  }
}

function encode(name, message, { version = defaultVersion } = {}) {
  const state = { buffer: null, start: 0, end: 0 };

  const route = getRouteByName(name);
  setVersion(version);

  c.uint.preencode(state, route.id);
  route.enc.preencode(state, message);

  state.buffer = b4a.allocUnsafe(state.end);
  c.uint.encode(state, route.id);
  route.enc.encode(state, message);

  return state.buffer;
}

function decode(buffer, { version = defaultVersion } = {}) {
  const state = { buffer, start: 0, end: buffer.length };

  const id = c.uint.decode(state);
  const route = getRouteById(id);
  setVersion(version);

  const value = route.enc.decode(state);
  return { id, name: route.name, value };
}

const route0 = {
  name: "@pear-chat/add-writer",
  id: 0,
  enc: getEncoding("@pear-chat/writer"),
};

const route1 = {
  name: "@pear-chat/add-invite",
  id: 1,
  enc: getEncoding("@pear-chat/invite"),
};

const route2 = {
  name: "@pear-chat/add-message",
  id: 2,
  enc: getEncoding("@pear-chat/message"),
};

function getRouteByName(name) {
  switch (name) {
    case "@pear-chat/add-writer":
      return route0;
    case "@pear-chat/add-invite":
      return route1;
    case "@pear-chat/add-message":
      return route2;
    default:
      throw DispatchError.ROUTE_NOT_FOUND_BY_NAME(name);
  }
}

function getRouteById(id) {
  switch (id) {
    case 0:
      return route0;
    case 1:
      return route1;
    case 2:
      return route2;
    default:
      throw DispatchError.HANDLER_NOT_FOUND_BY_ID(id);
  }
}

module.exports = {
  version,
  encode,
  decode,
  Router,
  DispatchError,
  ERRORS,
};
